# Site settings
title: Homepage of Qingtao Liu
email: Liu_qt@163.com
description: > # this means to ignore newlines until "baseurl:"
  Live and learn.
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "https://lqts.github.io/" # the base hostname & protocol for your site
username: Qingtao Liu
twitter_username: LQTS
github_username:  LQTS
GoogleAnalytics: 


#twitter:
#  username: rmsubekti
#facebook:
#  app_id: 1234567
#  publisher: 1234567

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:username'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'
